apiVersion: v1
kind: Secret
metadata:
  name: openim-mongo-secret
type: Opaque
data:
  mongo_openim_username: bWluaW9fcEM1d01C # base64 for "minio_pC5wMB", this user credentials need in authSource database.
  mongo_openim_password: ckk1N1BKc0pobnpfcWxSa2ZuVGEwUlBU # base64 for "rI57PJsJhnz_qlRkfnTa0RPT"
