openimsdk/my-open-im-docker:
  - source: ./config
    dest: ./my-open-im-server/release/config
    replace: true
  - source: ./docs
    dest: ./my-open-im-server/release/docs
    replace: true
  - source: ./scripts
    dest: ./my-open-im-server/release/scripts
    replace: true
  - source: ./scripts
    dest: ./scripts
    replace: false
  - source: ./Makefile
    dest: ./Makefile
    replace: false
