serviceBinaries:
  my-open-im-api: 1
  my-open-im-crontask: 4
  my-open-im-rpc-user: 1
  my-open-im-msggateway: 1
  my-open-im-push: 8
  my-open-im-msgtransfer: 8
  my-open-im-rpc-conversation: 1
  my-open-im-rpc-auth: 1
  my-open-im-rpc-group: 1
  my-open-im-rpc-friend: 1
  my-open-im-rpc-msg: 1
  my-open-im-rpc-third: 1
toolBinaries:
  - check-free-memory
  - check-component
  - seq
maxFileDescriptors: 10000
